annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Fixed adding rabbitmq queue to Event Service deployment
apiVersion: v2
appVersion: 1.2.2
dependencies:
- condition: postgresql.install
  name: postgresql
  repository: oci://europe-west3-docker.pkg.dev/rasa-releases/rasa-x-helm
  version: ~10.16.2
- condition: redis.install
  name: redis
  repository: oci://europe-west3-docker.pkg.dev/rasa-releases/rasa-x-helm
  version: ~15.7.6
- condition: rabbitmq.install
  name: rabbitmq
  repository: oci://europe-west3-docker.pkg.dev/rasa-releases/rasa-x-helm
  version: ~8.32.2
description: Rasa Enterprise Helm chart for Kubernetes / Openshift
home: https://github.com/RasaHQ/rasa-x-helm
icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqZPsa-h0ilYPCFaQmf21MFMyVH7oyvrfnJHwvGOJVlMIeTiakBJTSwGd2cDFcF5AsEiY&usqp=CAU
keywords:
- Rasa
- AI Assistants
- Chatbot
- Rasa Enterprise
maintainers:
- email: tom@rasa.com
  name: tmbo
  url: https://rasa.com
name: rasa-x
version: 4.5.22
